---
title: "tirage-aleatoire"
author: "Rémi_Lafitte"
date: "09/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(infer)
library(patchwork)
library(magrittr)
library(tidyverse)

```

## tirage aleatoire

- Création de 4 populations. les populations i sont identiques. les populations d sont différentes.

```{r}
i1<- rnorm(n = 20, mean = 400, sd = 10) %>% as_tibble(.)
i2 = i1
d1<- rnorm(n = 20, mean = 450, sd = 13) %>% as_tibble(.)
d2<- rnorm(n = 20, mean = 650, sd = 16) %>% as_tibble(.)

```

- 6 tirages de 4 echantillons aleatoires

```{r}
tirage_i1 <- i1 %>% 
  rep_sample_n(size = 4, reps = 6) %>% 
  group_by(replicate) %>% 
  summarise(mean = mean(value)) %>% 
  ungroup()

tirage_i2 <- i2 %>% 
  rep_sample_n(size = 4, reps = 6) %>% 
  group_by(replicate) %>% 
  summarise(mean = mean(value)) %>% 
  ungroup()

p1<-ggplot(tirage_i1,aes(x = replicate, y = mean)) +
  geom_point(size = 2) +
  geom_hline(yintercept = mean(tirage_i1$mean), col = "red")+
  scale_x_continuous(breaks=seq(1, 6, 1))
  

p2<-ggplot(tirage_i2,aes(x = replicate, y = mean)) +
  geom_point(size = 2)+
  geom_hline(yintercept = mean(tirage_i2$mean), col = "blue")+
  scale_x_continuous(breaks=seq(1, 6, 1))


p1+p2
  
  
```


```{r}
tirage_d1 <- d1 %>% 
  rep_sample_n(size = 4, reps = 6) %>% 
  group_by(replicate) %>% 
  summarise(mean = mean(value)) %>% 
  ungroup()

tirage_d2 <- d2 %>% 
  rep_sample_n(size = 4, reps = 6) %>% 
  group_by(replicate) %>% 
  summarise(mean = mean(value)) %>% 
  ungroup()

p3<-ggplot(tirage_d1,aes(x = replicate, y = mean)) +
  geom_point(size = 2) +
  geom_hline(yintercept = mean(tirage_d1$mean), col = "red")+
  scale_x_continuous(breaks=seq(1, 6, 1))
  

p4<-ggplot(tirage_d2,aes(x = replicate, y = mean)) +
  geom_point(size = 2)+
  geom_hline(yintercept = mean(tirage_d2$mean), col = "blue")+
  scale_x_continuous(breaks=seq(1, 6, 1))


p3+p4
  
  
```